import requests,json,time,threading,os,sys
import urllib.request, os, threading, time, random, sys
import colorama
from colorama import Fore, Style, init
#from requests_futures.sessions import FuturesSession
#from requests_futures import sessions
os.system("clear")
print(Fore.RED + "Spam Gmail V2")
print("")
print(Fore.YELLOW + "      ---------------------------------")
print(Fore.BLUE + "                 Spam Gmail")
print(Fore.YELLOW + "      ---------------------------------")
y = input(Fore.RED + "Gmail : ")
m = input(Fore.GREEN + "messenger : ")
j = input(Fore.BLUE + "Numbers : ")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
time.sleep(1)
print(Fore.YELLOW + f"send to {y} Done")
